# Generated by Django 4.2.1 on 2023-06-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_rename_name_booking_resident_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='resident_name',
            new_name='resident',
        ),
    ]
